name: "Hello World JS Action"
description: "Greet someone and record the time"

inputs:
    who_to_greet:
        description: "Who to greet"
        required: true
        default: "World"
    whotogreet:
        description: "Who to greet"
        required: true
        default: "World2"
    peca: { description: "Uma peca", required: false }
    tra-vao: { description: "Uma travao", required: false }
    volante: { description: "Uma volante", required: false }

outputs:
    time:
        description: "The time we greeted you"

runs:
    using: docker
    # Use a final build, when reaching a stable-release
    #image: docker://ghcr.io/unitedbycode/alfredo:sha-c780c4b
    image: Dockerfile
    env:
      foobarthis: ${{ inputs.who_to_greet }}
#    args:
#      - ${{ inputs.who_to_greet }}
#      - ${{ inputs.peca }}
