name: Build Alfredo - Base Docker Image

on:
  workflow_dispatch:

jobs:
  build-base-image:
    uses: ./.github/workflows/reusable-build-docker-image.yml
    with:
      context: .
      dockerfile: Dockerfile
      username: unitedbycode
      image_name: unitedbycode/alfredo
      platforms: linux/amd64
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
