name: Build Alfredo - Base Docker Image

on:
  workflow_dispatch:
  push:
    paths:
      - 'base.Dockerfile'
      - 'package**.json'
      - 'entrypoint.sh'
    branches:
      - main

jobs:
  build-base-image:
    uses: ./.github/workflows/reusable-build-docker-image.yml
    with:
      context: .
      dockerfile: base.Dockerfile
      username: unitedbycode
      image_name: unitedbycode/alfredo
      platforms: linux/amd64
